### ISSUE TITLE
Documentation is missing database creation info

### ISSUE THREAD

**Issue by amureki** [DjangoGirls/djangogirls#254] opened 2016-04-02 18:05 UTC
The documentation is really good, but it missing part about database creation. Only migrations command provided.

So, it could be a good option to start with committing here - just to add a few commands about how to create new database and add a new user or role there.

Just fork the repo, update the README, and submit a pull request to fix this.

Thanks!

**Comment by patjouk** [comment] 2016-04-03 13:45
That's a duplicate of #192

**Closed by patjouk** 2016-04-03 13:45 UTC
